[package]
name = "imapsieve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = {version = "3.0.0-alpha.12"}
sieve-rs = "0.4.0"
